server:
  port: 9527

spring:
  application:
    name: xcx-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /cqrcb
  ignored-services: "*"
  routes:
    mydept.serviceId: xcx-act
    mydept.path: /myact/**

info:
  app.name: xcx-act
  company.name: www.xcx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

