spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  application:
    name: xcx-act
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/xcx8001?characterEncoding=utf8&useSSL=false&serverTimezone=UTC              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.cqrcb.xcx.entity    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: xcx-act-8001
    refer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: xcx-act
  company.name: www.xcx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$