server:
  port: 3344

spring:
  application:
    name:  xcx-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eduardljh/xcx-config.git
          username: javaljh@163.com
          password: liangjunhua5


